define([], function() {
  return {
    "DebugLayoutOption": "Debug",
    "FilterParameter": "vrednost $filter parametra",
    "InvalidNumberIntervalMessage": "Vrednost mora biti med 1 in 999",
    "NoResultMessage": "Nobenih najdenih elementov",
    "OrderByParameter": "vrednost $orderby parametra",
    "PageSizeParameter": "Število zapisov na stran",
    "PeopleLayoutOption": "Ljudje",
    "PlaceHolderEditLabel": "Uredi",
    "PlaceHolderConfigureBtnLabel": "Nastavi",
    "PlaceHolderIconText": "Isklanik uporabnikov",
    "PlaceHolderDescription": "Komponenta za iskanje v storitvi Microsoft Graph",
    "QuerySettingsGroupName": "Poizvedba",
    "ResultsLayoutLabel": "Izgled rezultatov",
    "ResultsCount": "{0} zadetkov",
    "SearchInputPlaceholder": "Vpišite iskalne kriterije",
    "SearchParameter": "vrednost $search parametra",
    "SearchParameterOption": "vrednost $search parametra",
    "NoneSearchParameterOption": "Nič",
    "StaticSearchParameterOption": "Statična poizvedba",
    "BoxSearchParameterOption": "Iskalno polje",
    "DynamicSearchParameterOption": "Dinamični podatki",
    "SearchQuerySettingsGroupName": "Iskalni parametri",
    "SelectParameter": "vrednost $select parametra",
    "ShowPaginationControl": "Prikaži številke strani",
    "ShowLivePersonaCard": "Prikaži živo kartico uporabnika",
    "ShowResultsCountLabel": "Prikaži število zadetkov",
    "ShowBlankLabel": "Prikaži prazno komponento če ni zadetkov",
    "ShowBlankEditInfoMessage": "Poizvedba ni vrnila nobenih rezultatov.",
    "StylingSettingsGroupName": "Nastavitve izgleda",
    "TemplateParameters": {
      "TemplateParametersGroupName": "Nastavitve predloge",
      "ManagePeopleFieldsLabel": "Upravljaj s polji v kartici",
      "ManagePeopleFieldsPanelDescriptionLabel": "Tukaj lahko povežete posamezna polja z kartico uporabnika",
      "PlaceholderNameFieldLabel": "Naziv",
      "PlaceholderValueFieldLabel": "Vrednost",
      "PersonaSizeOptionsLabel": "Velikost slike",
      "PersonaSizeExtraSmall": "Zelo majhna",
      "PersonaSizeSmall": "Majhna",
      "PersonaSizeRegular": "Normalna",
      "PersonaSizeLarge": "Velika",
      "PersonaSizeExtraLarge": "Zelo velika",
    },
  }
});